// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Manually maintained to keep parity with Rust IPC signatures.

/** user-defined commands **/

export const commands = {
	async getAppSettings(): Promise<Result<AppSettings, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listAiConfigs(): Promise<Result<AiConfigSafe[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_ai_configs") };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createAiConfig(input: CreateAiConfigInput): Promise<Result<AiConfigSafe, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_ai_config", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateAiConfig(input: UpdateAiConfigInput): Promise<Result<AiConfigSafe, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_ai_config", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteAiConfig(input: DeleteAiConfigInput): Promise<Result<DeleteAiConfigResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_ai_config", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async getTeacherProfile(): Promise<Result<TeacherProfile, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("get_teacher_profile") };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listTasks(): Promise<Result<TaskSummary[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_tasks") };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listPendingApprovals(): Promise<Result<ApprovalRequest[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_pending_approvals") };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async healthCheck(): Promise<Result<HealthCheckResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("health_check") };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async exportSemesterComments(input: ExportSemesterCommentsInput): Promise<Result<ExportSemesterCommentsResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("export_semester_comments", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async importStudents(input: ImportStudentsInput): Promise<Result<ImportStudentsResult, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("import_students", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listClassrooms(): Promise<Result<Classroom[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_classrooms") };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async getClassroom(id: string): Promise<Result<Classroom, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("get_classroom", { id }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createClassroom(input: CreateClassroomInput): Promise<Result<Classroom, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_classroom", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateClassroom(input: UpdateClassroomInput): Promise<Result<Classroom, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_classroom", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteClassroom(input: DeleteClassroomInput): Promise<Result<DeleteClassroomResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_classroom", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listStudents(input: ListStudentsInput): Promise<Result<Student[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_students", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async getStudent(id: string): Promise<Result<Student, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("get_student", { id }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createStudent(input: CreateStudentInput): Promise<Result<Student, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_student", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateStudent(input: UpdateStudentInput): Promise<Result<Student, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_student", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteStudent(input: DeleteStudentInput): Promise<Result<DeleteStudentResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_student", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async getStudentProfile360(id: string): Promise<Result<StudentProfile360, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("get_student_profile_360", { id }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listStudentTags(input: ListStudentTagsInput): Promise<Result<StudentTag[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_student_tags", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async addStudentTag(input: AddStudentTagInput): Promise<Result<StudentTag, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("add_student_tag", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async removeStudentTag(input: RemoveStudentTagInput): Promise<Result<RemoveStudentTagResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("remove_student_tag", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateStudentTag(input: UpdateStudentTagInput): Promise<Result<StudentTag, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_student_tag", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listStudentScores(input: ListStudentScoresInput): Promise<Result<ScoreRecord[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_student_scores", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createScoreRecord(input: CreateScoreRecordInput): Promise<Result<ScoreRecord, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_score_record", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateScoreRecord(input: UpdateScoreRecordInput): Promise<Result<ScoreRecord, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_score_record", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteScoreRecord(input: DeleteScoreRecordInput): Promise<Result<DeleteScoreRecordResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_score_record", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listStudentObservations(
		input: ListStudentObservationsInput,
	): Promise<Result<ObservationNote[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_student_observations", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createObservationNote(input: CreateObservationNoteInput): Promise<Result<ObservationNote, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_observation_note", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateObservationNote(input: UpdateObservationNoteInput): Promise<Result<ObservationNote, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_observation_note", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteObservationNote(
		input: DeleteObservationNoteInput,
	): Promise<Result<DeleteObservationNoteResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_observation_note", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listParentCommunications(
		input: ListParentCommunicationsInput,
	): Promise<Result<ParentCommunication[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_parent_communications", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createParentCommunication(
		input: CreateParentCommunicationInput,
	): Promise<Result<ParentCommunication, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_parent_communication", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateParentCommunication(
		input: UpdateParentCommunicationInput,
	): Promise<Result<ParentCommunication, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_parent_communication", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteParentCommunication(
		input: DeleteParentCommunicationInput,
	): Promise<Result<DeleteParentCommunicationResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_parent_communication", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listScheduleEvents(input: ListScheduleEventsInput): Promise<Result<ScheduleEvent[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_schedule_events", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async getScheduleEvent(id: string): Promise<Result<ScheduleEvent, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("get_schedule_event", { id }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createScheduleEvent(input: CreateScheduleEventInput): Promise<Result<ScheduleEvent, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_schedule_event", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateScheduleEvent(input: UpdateScheduleEventInput): Promise<Result<ScheduleEvent, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_schedule_event", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteScheduleEvent(
		input: DeleteScheduleEventInput,
	): Promise<Result<DeleteScheduleEventResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_schedule_event", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listScheduleFiles(input: ListScheduleFilesInput): Promise<Result<ScheduleFile[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_schedule_files", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createScheduleFile(input: CreateScheduleFileInput): Promise<Result<ScheduleFile, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_schedule_file", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteScheduleFile(input: DeleteScheduleFileInput): Promise<Result<DeleteScheduleFileResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_schedule_file", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listSemesterComments(input: ListSemesterCommentsInput): Promise<Result<SemesterComment[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_semester_comments", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createSemesterComment(input: CreateSemesterCommentInput): Promise<Result<SemesterComment, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_semester_comment", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateSemesterComment(input: UpdateSemesterCommentInput): Promise<Result<SemesterComment, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_semester_comment", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteSemesterComment(
		input: DeleteSemesterCommentInput,
	): Promise<Result<DeleteSemesterCommentResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_semester_comment", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async batchAdoptSemesterComments(input: BatchAdoptInput): Promise<Result<SemesterComment[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("batch_adopt_semester_comments", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listActivityAnnouncements(
		input: ListActivityAnnouncementsInput,
	): Promise<Result<ActivityAnnouncement[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_activity_announcements", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createActivityAnnouncement(
		input: CreateActivityAnnouncementInput,
	): Promise<Result<ActivityAnnouncement, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_activity_announcement", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateActivityAnnouncement(
		input: UpdateActivityAnnouncementInput,
	): Promise<Result<ActivityAnnouncement, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_activity_announcement", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteActivityAnnouncement(
		input: DeleteActivityAnnouncementInput,
	): Promise<Result<DeleteActivityAnnouncementResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_activity_announcement", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async generateParentCommunication(
		input: GenerateParentCommInput,
	): Promise<Result<ParentCommunication, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("generate_parent_communication", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async regenerateParentCommunication(
		input: RegenerateParentCommInput,
	): Promise<Result<ParentCommunication, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("regenerate_parent_communication", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async generateSemesterComment(input: GenerateSemesterCommentInput): Promise<Result<SemesterComment, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("generate_semester_comment", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async generateSemesterCommentsBatch(input: GenerateBatchCommentsInput): Promise<Result<AsyncTask, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("generate_semester_comments_batch", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async getBatchTaskProgress(taskId: string): Promise<Result<AsyncTask, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("get_batch_task_progress", { taskId }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async generateActivityAnnouncement(
		input: GenerateActivityAnnouncementInput,
	): Promise<Result<ActivityAnnouncement, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("generate_activity_announcement", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async searchEvidence(input: MemorySearchInput): Promise<Result<SearchEvidenceResult, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("search_evidence", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async initStudentMemory(input: InitStudentMemoryInput): Promise<Result<string, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("init_student_memory", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async readStudentMemoryTimeline(input: ReadMemoryTimelineInput): Promise<Result<MemoryEntry[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("read_student_memory_timeline", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async readStudentMemoryByTopic(input: ReadMemoryByTopicInput): Promise<Result<MemoryEntry[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("read_student_memory_by_topic", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async readStudentCommentMaterials(input: ReadCommentMaterialsInput): Promise<Result<MemoryEntry[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("read_student_comment_materials", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async appendStudentMemoryNote(input: AppendMemoryNoteInput): Promise<Result<null, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("append_student_memory_note", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async checkSensitiveContent(input: CheckSensitiveInput): Promise<Result<SensitiveInfoResult, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("check_sensitive_content", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async listTemplateFiles(input: ListTemplateFilesInput): Promise<Result<TemplateFile[], AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("list_template_files", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async getTemplateFile(id: string): Promise<Result<TemplateFile, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("get_template_file", { id }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async createTemplateFile(input: CreateTemplateFileInput): Promise<Result<TemplateFile, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("create_template_file", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async updateTemplateFile(input: UpdateTemplateFileInput): Promise<Result<TemplateFile, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("update_template_file", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
	async deleteTemplateFile(input: DeleteTemplateFileInput): Promise<Result<DeleteTemplateFileResponse, AppError>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("delete_template_file", { input }) };
		} catch (e) {
			return { status: "error", error: e as any };
		}
	},
};

/** user-defined types **/

export type AppError =
	| { Database: string }
	| { Config: string }
	| { FileOperation: string }
	| { TaskExecution: string }
	| { InvalidInput: string }
	| { NotFound: string }
	| { PermissionDenied: string }
	| { ExternalService: string }
	| { Internal: string };

export type AppSettings = { workspace_path: string; ai_provider: string; language: string };
export type ApprovalRequest = {
	id: string;
	request_type: string;
	action_summary: string;
	risk_level: string;
	status: string;
};
export type HealthCheckResponse = { status: string; version: string; db_connected: boolean };
export type TeacherProfile = {
	id: string;
	name: string;
	stage: string;
	subject: string;
	textbook_version: string | null;
	tone_preset: string | null;
	is_deleted: number;
	created_at: string;
	updated_at: string;
};
export type TaskSummary = { id: string; task_type: string; status: string; created_at: string };

export type AiConfigSafe = {
	id: string;
	provider_name: string;
	display_name: string;
	base_url: string;
	has_api_key: boolean;
	default_model: string;
	is_active: number;
	config_json: string | null;
	created_at: string;
	updated_at: string;
};
export type CreateAiConfigInput = {
	provider_name: string;
	display_name: string;
	base_url: string;
	api_key: string;
	default_model: string;
	is_active: boolean | null;
	config_json: string | null;
};
export type UpdateAiConfigInput = {
	id: string;
	display_name: string | null;
	base_url: string | null;
	api_key: string | null;
	default_model: string | null;
	is_active: boolean | null;
	config_json: string | null;
};
export type DeleteAiConfigInput = { id: string };
export type DeleteAiConfigResponse = { success: boolean };

export type Classroom = {
	id: string;
	grade: string;
	class_name: string;
	subject: string;
	teacher_id: string;
	is_deleted: number;
	created_at: string;
	updated_at: string;
};
export type CreateClassroomInput = { grade: string; class_name: string; subject: string; teacher_id: string };
export type UpdateClassroomInput = {
	id: string;
	grade: string | null;
	class_name: string | null;
	subject: string | null;
	teacher_id: string | null;
};
export type DeleteClassroomInput = { id: string };
export type DeleteClassroomResponse = { success: boolean };

export type Student = {
	id: string;
	student_no: string;
	name: string;
	gender: string | null;
	class_id: string;
	meta_json: string | null;
	folder_path: string;
	is_deleted: number;
	created_at: string;
	updated_at: string;
};
export type CreateStudentInput = {
	student_no: string;
	name: string;
	gender: string | null;
	class_id: string;
	meta_json: string | null;
};
export type UpdateStudentInput = {
	id: string;
	student_no: string | null;
	name: string | null;
	gender: string | null;
	class_id: string | null;
	meta_json: string | null;
};
export type ListStudentsInput = { class_id: string | null };
export type DeleteStudentInput = { id: string };
export type DeleteStudentResponse = { success: boolean };
export type StudentProfile360 = {
	student: Student;
	tags: StudentTag[];
	recent_scores: ScoreRecord[];
	recent_observations: ObservationNote[];
	recent_communications: ParentCommunication[];
};

export type StudentTag = { id: string; student_id: string; tag_name: string; is_deleted: number; created_at: string };
export type ListStudentTagsInput = { student_id: string };
export type AddStudentTagInput = { student_id: string; tag_name: string };
export type RemoveStudentTagInput = { id: string };
export type RemoveStudentTagResponse = { success: boolean };
export type UpdateStudentTagInput = { id: string; tag_name: string };

export type ScoreRecord = {
	id: string;
	student_id: string;
	exam_name: string;
	subject: string;
	score: number;
	full_score: number;
	rank_in_class: number | null;
	exam_date: string;
	is_deleted: number;
	updated_at: string;
};
export type ListStudentScoresInput = {
	student_id: string;
	subject: string | null;
	from_date: string | null;
	to_date: string | null;
};
export type CreateScoreRecordInput = {
	student_id: string;
	exam_name: string;
	subject: string;
	score: number;
	full_score: number;
	rank_in_class: number | null;
	exam_date: string;
};
export type UpdateScoreRecordInput = {
	id: string;
	exam_name: string | null;
	subject: string | null;
	score: number | null;
	full_score: number | null;
	rank_in_class: number | null;
	exam_date: string | null;
};
export type DeleteScoreRecordInput = { id: string };
export type DeleteScoreRecordResponse = { success: boolean };

export type ObservationNote = {
	id: string;
	student_id: string;
	content: string;
	source: string | null;
	created_at: string;
	is_deleted: number;
	updated_at: string;
};
export type ListStudentObservationsInput = { student_id: string; limit: number | null; offset: number | null };
export type CreateObservationNoteInput = { student_id: string; content: string; source: string | null };
export type UpdateObservationNoteInput = { id: string; content: string | null; source: string | null };
export type DeleteObservationNoteInput = { id: string };
export type DeleteObservationNoteResponse = { success: boolean };

export type ParentCommunication = {
	id: string;
	student_id: string;
	draft: string | null;
	adopted_text: string | null;
	status: string | null;
	evidence_json: string | null;
	created_at: string;
	is_deleted: number;
	updated_at: string;
};
export type ListParentCommunicationsInput = { student_id: string };
export type CreateParentCommunicationInput = {
	student_id: string;
	draft: string | null;
	adopted_text: string | null;
	status: string | null;
	evidence_json: string | null;
};
export type UpdateParentCommunicationInput = {
	id: string;
	draft: string | null;
	adopted_text: string | null;
	status: string | null;
	evidence_json: string | null;
};
export type DeleteParentCommunicationInput = { id: string };
export type DeleteParentCommunicationResponse = { success: boolean };

export type ScheduleEvent = {
	id: string;
	class_id: string;
	title: string;
	start_at: string;
	end_at: string | null;
	linked_file_id: string | null;
	is_deleted: number;
	created_at: string;
};
export type ListScheduleEventsInput = { class_id: string };
export type CreateScheduleEventInput = {
	class_id: string;
	title: string;
	start_at: string;
	end_at: string | null;
	linked_file_id: string | null;
};
export type UpdateScheduleEventInput = {
	id: string;
	title: string | null;
	start_at: string | null;
	end_at: string | null;
	linked_file_id: string | null;
};
export type DeleteScheduleEventInput = { id: string };
export type DeleteScheduleEventResponse = { success: boolean };

export type ScheduleFile = {
	id: string;
	class_id: string;
	file_name: string;
	file_path: string;
	file_type: string | null;
	file_size: number | null;
	is_deleted: number;
	created_at: string;
};
export type ListScheduleFilesInput = { class_id: string };
export type CreateScheduleFileInput = {
	class_id: string;
	file_name: string;
	file_path: string;
	file_type: string | null;
	file_size: number | null;
};
export type DeleteScheduleFileInput = { id: string };
export type DeleteScheduleFileResponse = { success: boolean };

export type ImportDuplicateStrategy = "Skip" | "Update" | "Add";
export type ImportStudentsInput = {
	file_path: string;
	class_id: string;
	duplicate_strategy: ImportDuplicateStrategy;
};
export type ImportRowError = { row_number: number; field: string; reason: string; suggestion: string };
export type ImportStudentsResult = {
	total_rows: number;
	created_count: number;
	updated_count: number;
	skipped_count: number;
	error_count: number;
	errors: ImportRowError[];
};

export type EvidenceItem = {
	content: string;
	source_table: string;
	source_id: string;
	student_id: string;
	class_id: string | null;
	created_at: string;
	score: number;
	file_path: string | null;
	subject: string | null;
};
export type MemorySearchInput = {
	keyword: string | null;
	student_id: string | null;
	class_id: string | null;
	from_date: string | null;
	to_date: string | null;
	subject: string | null;
	source_table: string | null;
	top_k: number | null;
	workspace_path: string | null;
};
export type SearchEvidenceResult = { items: EvidenceItem[]; total_before_dedup: number; returned_count: number };

export type MemoryEntry = {
	date: string | null;
	subject: string | null;
	entry_type: string | null;
	content: string;
	section: string;
	source_file: string;
};
export type MemoryFileMeta = {
	student_id: string;
	student_name: string | null;
	class_id: string | null;
	homeroom_teacher_id: string | null;
	version: string | null;
	last_updated_at: string | null;
	file_path: string;
};
export type ReadMemoryTimelineInput = {
	student_id: string;
	from_date: string | null;
	to_date: string | null;
	section_filter: string[] | null;
	limit: number | null;
};
export type ReadMemoryByTopicInput = {
	student_id: string;
	topic: string;
	subject: string | null;
	top_k: number | null;
};
export type ReadCommentMaterialsInput = { student_id: string; term: string | null; subject: string | null };
export type AppendMemoryNoteInput = { student_id: string; section: string; content: string };
export type InitStudentMemoryInput = {
	student_id: string;
	student_name: string | null;
	class_id: string | null;
	homeroom_teacher_id: string | null;
};
export type CheckSensitiveInput = { content: string };
export type SensitiveInfoResult = { has_sensitive: boolean; violations: string[] };

export type SemesterComment = {
	id: string;
	student_id: string;
	task_id: string | null;
	term: string;
	draft: string | null;
	adopted_text: string | null;
	status: string;
	evidence_json: string | null;
	evidence_count: number;
	is_deleted: number;
	created_at: string;
	updated_at: string;
};
export type ListSemesterCommentsInput = {
	student_id: string | null;
	term: string | null;
	task_id: string | null;
};
export type CreateSemesterCommentInput = {
	student_id: string;
	task_id: string | null;
	term: string;
	draft: string | null;
	adopted_text: string | null;
	status: string | null;
	evidence_json: string | null;
	evidence_count: number | null;
};
export type UpdateSemesterCommentInput = {
	id: string;
	draft: string | null;
	adopted_text: string | null;
	status: string | null;
	evidence_json: string | null;
	evidence_count: number | null;
};
export type DeleteSemesterCommentInput = { id: string };
export type DeleteSemesterCommentResponse = { success: boolean };
export type BatchAdoptInput = { task_id: string };

export type ActivityAnnouncement = {
	id: string;
	class_id: string;
	title: string;
	topic: string | null;
	audience: string;
	draft: string | null;
	adopted_text: string | null;
	template_id: string | null;
	status: string;
	is_deleted: number;
	created_at: string;
	updated_at: string;
};
export type ListActivityAnnouncementsInput = { class_id: string; audience: string | null };
export type CreateActivityAnnouncementInput = {
	class_id: string;
	title: string;
	topic: string | null;
	audience: string | null;
	draft: string | null;
	adopted_text: string | null;
	template_id: string | null;
	status: string | null;
};
export type UpdateActivityAnnouncementInput = {
	id: string;
	title: string | null;
	topic: string | null;
	audience: string | null;
	draft: string | null;
	adopted_text: string | null;
	template_id: string | null;
	status: string | null;
};
export type DeleteActivityAnnouncementInput = { id: string };
export type DeleteActivityAnnouncementResponse = { success: boolean };

export type AsyncTask = {
	id: string;
	task_type: string;
	target_id: string | null;
	status: string;
	progress_json: string | null;
	context_data: string | null;
	checkpoint_cursor: string | null;
	completed_items_json: string | null;
	partial_output_path: string | null;
	lease_until: string | null;
	attempt_count: number;
	last_heartbeat_at: string | null;
	worker_id: string | null;
	error_code: string | null;
	error_message: string | null;
	created_at: string;
	updated_at: string;
};
export type CreateAsyncTaskInput = { task_type: string; target_id: string | null; context_data: string | null };
export type BatchProgress = {
	total: number;
	completed: number;
	failed: number;
	current_student_name: string | null;
};

export type ParentCommunicationDraft = { affirmation: string; issue: string; suggestion: string };
export type SemesterCommentDraft = { comment: string; highlights: string[]; improvements: string[] };
export type ActivityAnnouncementDraft = { announcement: string; key_points: string[] };
export type GenerateParentCommInput = { student_id: string; keyword: string | null; tone: string | null };
export type RegenerateParentCommInput = { id: string; tone: string | null };
export type GenerateSemesterCommentInput = {
	student_id: string;
	term: string;
	task_id: string | null;
	existing_comments_summary: string | null;
};
export type GenerateBatchCommentsInput = { class_id: string; term: string };
export type GenerateActivityAnnouncementInput = {
	class_id: string;
	title: string;
	topic: string | null;
	audience: string;
	template_id: string | null;
};
export type ExportSemesterCommentsInput = { task_id: string | null; term: string | null; file_path: string };
export type ExportSemesterCommentsResponse = { file_path: string; exported_count: number };

/** 校本模板文件 */
export type TemplateFile = {
	id: string;
	type: string;
	school_scope: string | null;
	version: string | null;
	file_path: string;
	enabled: number;
	is_deleted: number;
	created_at: string;
};
export type CreateTemplateFileInput = {
	type: string;
	school_scope: string | null;
	version: string | null;
	file_path: string;
	enabled: number | null;
};
export type UpdateTemplateFileInput = {
	id: string;
	type: string | null;
	school_scope: string | null;
	version: string | null;
	file_path: string | null;
	enabled: number | null;
};
export type ListTemplateFilesInput = {
	type: string | null;
	enabled: number | null;
};
export type DeleteTemplateFileInput = { id: string };
export type DeleteTemplateFileResponse = { success: boolean };

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy({} as __EventObj__<any>, {
		get: (_, event) => {
			const name = mappings[event as keyof T];
			return {
				listen: (cb: TAURI_API_EVENT.EventCallback<any>) =>
					TAURI_API_EVENT.listen(name, cb),
				once: (cb: TAURI_API_EVENT.EventCallback<any>) =>
					TAURI_API_EVENT.once(name, cb),
				emit: (payload: any) => TAURI_API_EVENT.emit(name, payload),
			};
		},
	}) as any as { [K in keyof T]: __EventObj__<T[K]> };
}
